POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Klive Hudler",
    "number" : "783-2345-8582"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Open Klugmann",
    "number" : "883-4585-2848"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Dan Abramov",
    "number" : "019-4462-2368"
}